name: SelfControl
version: '1.0'
main: cat6172.selfcontrol.SelfControl
description: Kick yourself
author: Cat6172
api-version: '1.20'

commands:
  toggleautokick:
    description: Add yourself to the list of players kicked next specified time period
    permission: selfcontrol.all
  toggleautotempban:
    description: Add yourself to the list of players temp banned next specified time period
    permission: selfcontrol.all
  selfcontrol:
    description: View list of players to be kicked, kick them
    permission: selfcontrol.admin
    usage: arguments are "list" to see players signed up and "now" to execute
permissions:
  selfcontrol.admin:
    description: view and execute kick/tempban list
    default: op
  selfcontrol.self:
    description: add self to list of next kick/tempban
    default: false
