name: SelfControl
version: '1.1'
main: cat6172.selfcontrol.SelfControl
description: Kick/tempban yourself at a specified time
author: Cat6172
api-version: '1.20'

commands:
  kickme:
    description: Add/remove yourself to the list of players kicked at specified time
    permission: selfcontrol.self
    usage: /kickme at [time, ie 1:34pm] (to add) or /kickme r (to remove)
  banme:
    description: Add/remove yourself to the list of players temp banned (1 hour) at specified time
    permission: selfcontrol.self
    usage: /banme set [time, ie 1:34pm] or /banme r (to remove)
permissions:
  selfcontrol.self:
    description: add self to auto kick/tempban
    default: false
