name: SelfControl
version: '1.0'
main: cat6172.selfcontrol.SelfControl
description: Kick yourself
author: Cat6172
api-version: '1.20'

commands:
  autokick:
    description: Add/remove yourself to the list of players kicked next specified time period
    permission: selfcontrol.all
    usage: /autokick set [time, ie 1:34pm] or /autokick remove
  autoban:
    description: Add/remove yourself to the list of players temp banned next specified time period
    permission: selfcontrol.all
    usage: /autoban set [time, ie 1:34pm] or /autoban remove
  selfcontrol:
    description: View list of players to be kicked or temp banned
    permission: selfcontrol.admin
    usage: arguments are "list" to see players signed up
permissions:
  selfcontrol.admin:
    description: view kick/tempban list
    default: op
  selfcontrol.self:
    description: add self to auto kick/tempban
    default: false
